### ISSUE TITLE
Improve structure of Storybook tests

### ISSUE THREAD

**Issue by essential-randomness** [BobaBoard/boba-components#80]
Some stories are in folders and some are not + the numbering is weird. Let's figure out a more intentional structure!

**Comment by virtuous-cat** [comment]
So what do we want to do with this? I can implement whatever we decide on as I work though other story related issues.

**Comment by essential-randomness** [comment]
@riazaia is the main complainer (I think) and an excellent restructurer of things, so I'd like to hear what she has/had in mind. I don't have well-formed opinions.

(Which makes me realize this should be tagged as design and not ready to implement. Woops.)

**Comment by virtuous-cat** [comment]
My 2 cents would be:
- everything into folders
- folders aren't numbered so they are just organized alphabetically
- stories in folders organized: default full component first, then variations, then sub-components, then any legacy stories last

**Comment by riazaia** [comment]
I'd like a structure somehwat analogous to the actual [components folder](https://github.com/BobaBoard/boba-components/tree/main/src), so in folders and without numbers, like @virtuous-cat said. This would also apply to the tests. I also like the numbering for the files inside each folder!

In terms of the actual storybook demo I think there's a couple things that currently don't make sense to me exactly, like having the bobadex inside the users preview (because I feel like you could display that in pages that aren't just the user page, maybe?) or having the board selector inside the tags folder, since that seems more of a "this dropdown is right next to the tags in our current layout" than "this is actually related to tags", but this might just be that I'm not used to the structure.

I think we should also have a section (called something like Outdated/In Development/Not Implemented/Experimental/Archived/A Name That Makes Sense) for things that aren't currently a part of the UI, like the reactions component because I feel like those components add confusion and clutter things up.

**Comment by essential-randomness** [comment]
I think you both have a really good pulse on the issues, and your ideas on how to make it all better are excellent. You have my blessing to move forward with the suggested structure.

It _is_ very possible that as you go about doing it there may be more nuances than we can see now, so do keep us posted.

To recap our choices:
1. Mimic the folder structure in [`src/`](https://github.com/BobaBoard/boba-components/tree/main/src) for our tests structure, with no numbers
2. A component's stories should go in the same-named folder as the original `src/` folder they're defined in.
3. Move variants that aren't currently "in production" to an `experimental` folder

I have one question about:
> stories in folders organized: default full component first (000), then variations (001...), then sub-components (101...), then any legacy stories last (201...)

Do you mean to have a 2-levels structure? e.g. `stories/layout/MenuBar/000-???.stories.tsx`? I feel like I don't fully understand what you're envisioning. Is it one story per file? I would like to keep variants (reasonably) tied together because it can be hard to go catch things across a lot of files, but maybe I'm not fully understanding this part of the proposal.

Also, here may be some stories that are testing how components fit/work together. Any idea on where to sort these?

**Comment by virtuous-cat** [comment]
I would suggest separating the not-in-production stories out into two folders: `legacy` and `experimental/in development`

Re: the folder/numbering system, you're right that most variations will be in the same file, but I was looking at the Posts folder as I was thinking this up, and for example, I would consider `PostQuote` a variant. So the Posts folder would look like: 
```
stories/post/000-Post.stories.tsx
stories/post/001-PostQuote.stories.tsx
stories/post/101-Card.stories.tsx
stories/post/102-PostHeader.stories.tsx
stories/post/103-PostFooter.stories.tsx
```
And obviously, if we're going to put the legacy stories in their own folder then we don't need the 200 level designation.

My intuition is that in practice we will find that most stories combining multiple components will still logically fit in one or another folder best. If not, we can make a separate folder for that sort of thing, though I don't have a good thought of what to call it. My brain is saying `gestalts` but seeing as we are trying to make this *less* confusing I don't think that's the way to go.

**Comment by essential-randomness** [comment]
I'm on board with this plan! Thank you for giving it so much thought.

**Comment by virtuous-cat** [comment]
Once I put all the stories in folders corresponding to their src folders,  I realized that my numbering system wasn't going to work because there isn't just one highest level component per folder. So I have instead done: X00 (starting at 100) for full components, X00b X00c etc. for variants, and X01 X02 etc. for sub-components.

So the Post folder looks like:
```
stories/post/100-Post.stories.tsx
stories/post/100b-CompactPostThread.stories.tsx
stories/post/100c-PostQuote.stories.tsx
stories/post/101-Card.stories.tsx
stories/post/102-PostHeader.stories.tsx
stories/post/103-PostFooter.stories.tsx
stories/post/200-Comment.stories.tsx
stories/post/200b-ChainComment.stories.tsx
stories/post/300-PostEditor.stories.tsx
stories/post/400-CommentEditor.stories.tsx
```
